### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by henkjan** [nylen/gnucash-django#1]
What is supposed to be configured at?    (**_GNUCASH ACCOUNT PATH**_), Do i need to provide a path to a .gnucash file?

**Comment by nylen** [comment]
No, your GnuCash data must be stored in a SQL database in order to use `gnucash-django` (first item under [Requirements](https://github.com/nylen/gnucash-django#requirements)).

The [`ACCOUNTS_LIST` setting](https://github.com/nylen/gnucash-django/blob/df608f5077fbb93a002a65d2d18e8449f5794fb6/settings.example.py#L158-L161) controls which accounts are listed in the index page (this should be your "important" accounts like bank accounts you always want to keep track of).  An "account path" is the path to a GnuCash account in your account tree, like the example I provided: `Assets:Current Assets:BANK ACCOUNT NAME`.
